#!/usr/bin/env bats

bats_require_minimum_version 1.5.0

# Tests for `scripts/install-agents.sh rules-sync`
#
# Slice 1: generate .claude/rules/*.md from agents/rules/*.md — path-scoped and
# always-apply cases.
# Slice 2: generate .cursor/rules/*.mdc alongside it.
#
# Isolation strategy: --source / --claude-dest / --cursor-dest point at
# tmpdirs, never the repo's own agents/rules, .claude/rules, .cursor/rules.
#
# Assertions use cmp against a byte-exact expected fixture rather than bats'
# $output (which strips leading/trailing newlines) — byte fidelity of the
# body, including its leading blank line or lack of one, is the property
# under test.

INSTALL_SCRIPT="$BATS_TEST_DIRNAME/../scripts/install-agents.sh"
rules-sync() { "$INSTALL_SCRIPT" rules-sync "$@"; }
SCRIPT=rules-sync

setup() {
  SRC=$(mktemp -d)
  DEST=$(mktemp -d)
  CURSOR_DEST=$(mktemp -d)
}

teardown() {
  rm -rf "$SRC" "$DEST" "$CURSOR_DEST"
}

write_sql_comments_source() {
  cat > "$SRC/sql-comments.md" <<'EOF'
---
claude:
  paths:
    - "**/*.sql"
cursor:
  globs: "**/*.sql"
---
Always add COMMENT clauses to tables and columns.
EOF
}

write_always_apply_source() {
  local name="$1" body="$2"
  cat > "$SRC/$name.md" <<EOF
---
claude: {}
cursor:
  alwaysApply: true
---
$body
EOF
}

write_way_of_work_source() {
  cat > "$SRC/way-of-work.md" <<'EOF'
---
claude: {}
cursor:
  alwaysApply: true
---

Follow the acceptance loop.
EOF
}

@test "a path-scoped rule's claude block is promoted to the generated file's own frontmatter" {
  write_sql_comments_source

  cat > "$DEST/expected-sql-comments.md" <<'EOF'
---
paths:
  - "**/*.sql"
---
Always add COMMENT clauses to tables and columns.
EOF

  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]

  [ -f "$DEST/sql-comments.md" ]
  cmp "$DEST/sql-comments.md" "$DEST/expected-sql-comments.md"
}

@test "an always-apply rule with an empty claude block is generated with no frontmatter" {
  write_way_of_work_source

  cat > "$DEST/expected-way-of-work.md" <<'EOF'

Follow the acceptance loop.
EOF

  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]

  [ -f "$DEST/way-of-work.md" ]
  cmp "$DEST/way-of-work.md" "$DEST/expected-way-of-work.md"
}

@test "a source file with no frontmatter block is skipped, and other files still sync" {
  printf 'No frontmatter here, just prose.\n' > "$SRC/no-frontmatter.md"
  write_sql_comments_source

  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]

  [ ! -f "$DEST/no-frontmatter.md" ]
  [ -f "$DEST/sql-comments.md" ]
}

@test "a path-scoped rule's cursor block is promoted to a .mdc file with a .mdc extension" {
  write_sql_comments_source

  cat > "$CURSOR_DEST/expected-sql-comments.mdc" <<'EOF'
---
globs: "**/*.sql"
---
Always add COMMENT clauses to tables and columns.
EOF

  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]

  [ -f "$CURSOR_DEST/sql-comments.mdc" ]
  cmp "$CURSOR_DEST/sql-comments.mdc" "$CURSOR_DEST/expected-sql-comments.mdc"
}

@test "an always-apply rule's cursor alwaysApply block is promoted to a .mdc file" {
  write_way_of_work_source

  cat > "$CURSOR_DEST/expected-way-of-work.mdc" <<'EOF'
---
alwaysApply: true
---

Follow the acceptance loop.
EOF

  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]

  [ -f "$CURSOR_DEST/way-of-work.mdc" ]
  cmp "$CURSOR_DEST/way-of-work.mdc" "$CURSOR_DEST/expected-way-of-work.mdc"
}

@test "a rule with an empty cursor block generates a .mdc file with no frontmatter and warns it will not auto-attach" {
  cat > "$SRC/orphan-cursor.md" <<'EOF'
---
claude:
  paths:
    - "**/*.sql"
cursor: {}
---
Body text.
EOF

  run --separate-stderr "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]
  sync_stderr="$stderr"

  [ -f "$CURSOR_DEST/orphan-cursor.mdc" ]
  run cat "$CURSOR_DEST/orphan-cursor.mdc"
  [ "$output" = "Body text." ]
  [[ "$sync_stderr" == *"orphan-cursor.md"* ]]
  [[ "$sync_stderr" == *"will not auto-attach"* ]]
}

@test "removing a source rule deletes its previously generated claude and cursor files on the next run" {
  write_always_apply_source rule-a "Rule A body."
  write_always_apply_source rule-b "Rule B body."

  "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ -f "$DEST/rule-a.md" ]
  [ -f "$DEST/rule-b.md" ]
  [ -f "$CURSOR_DEST/rule-a.mdc" ]
  [ -f "$CURSOR_DEST/rule-b.mdc" ]

  rm "$SRC/rule-b.md"
  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]

  [ -f "$DEST/rule-a.md" ]
  [ ! -f "$DEST/rule-b.md" ]
  [ -f "$CURSOR_DEST/rule-a.mdc" ]
  [ ! -f "$CURSOR_DEST/rule-b.mdc" ]
}

@test "a destination file never generated by rules-sync is left alone during pruning" {
  write_always_apply_source rule-a "Rule A body."

  "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ -f "$DEST/rule-a.md" ]

  echo "hand-written, not generated" > "$DEST/hand-made.md"

  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"
  [ "$status" -eq 0 ]

  [ -f "$DEST/hand-made.md" ]
}

@test "--dry-run reports what it would generate without creating destinations or writing files" {
  write_always_apply_source rule-a "Rule A body."
  local claude_dest="$DEST/generated"
  local cursor_dest="$CURSOR_DEST/generated"

  run "$SCRIPT" --source "$SRC" --claude-dest "$claude_dest" --cursor-dest "$cursor_dest" --dry-run
  [ "$status" -eq 0 ]

  [[ "$output" == *"gen   rule-a.md"* ]]
  [[ "$output" == *"gen   rule-a.mdc"* ]]
  [ ! -d "$claude_dest" ]
  [ ! -d "$cursor_dest" ]
}

@test "--dry-run reports a pending prune without deleting the file or touching the manifest" {
  write_always_apply_source rule-a "Rule A body."
  write_always_apply_source rule-b "Rule B body."
  "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST"

  rm "$SRC/rule-b.md"
  run "$SCRIPT" --source "$SRC" --claude-dest "$DEST" --cursor-dest "$CURSOR_DEST" --dry-run
  [ "$status" -eq 0 ]

  [[ "$output" == *"prune rule-b.md"* ]]
  [ -f "$DEST/rule-b.md" ]
  grep -qx "rule-b.md" "$DEST/.rules-sync-manifest"
}
