[tools]
btop = "latest"
eza = "latest"
neovim = "latest"
node = "20"
tmux = "latest"
lazygit = "latest"
vale = "latest"
fzf = "latest"
bats = "latest"
lua = "latest"
luau = "latest"
luajit = "latest"
ruby = "latest"
ripgrep = "latest"
fd = "latest"
"go:golang.org/x/tools/gopls" = "latest"

[settings.ruby]
compile = false
